#!/usr/bin/env python3
"""Extract the clean (open-weight-only) subset from the full corpus.

Reads every corpus JSON entry, keeps only those generated by open-weight
models (no Claude, no GPT, no proprietary APIs), and writes selected
entries to clean/.  Also produces clean/manifest.json.

Open-weight models currently included:
  - deepseek-chat (DeepSeek)
  - Any model name containing "qwen" or "llama"
  - Mechanical generators (deterministic transforms, no model IP)

Excluded (proprietary):
  - claude-*        (Anthropic)
  - gpt-*           (OpenAI)
  - grok-*          (xAI)
  - gemini-*        (Google)

Usage::

    python scripts/extract_clean.py
    python scripts/extract_clean.py --corpus-dir corpus --output-dir clean --limit 200

Story 10.7.7 -- Clean subset for D13=E publication.
"""
from __future__ import annotations

import argparse
import json
import random
import shutil
import sys
from pathlib import Path

# Models considered open-weight for clean subset
OPEN_WEIGHT_PREFIXES = [
    "deepseek",
    "qwen",
    "llama",
    "mechanical-",      # deterministic transforms, no model IP
]

PROPRIETARY_PREFIXES = [
    "claude-",
    "gpt-",
    "grok-",
    "gemini-",
]


def is_open_weight(model: str) -> bool:
    """Return True if model is open-weight."""
    model_lower = model.lower()
    for prefix in PROPRIETARY_PREFIXES:
        if model_lower.startswith(prefix):
            return False
    for prefix in OPEN_WEIGHT_PREFIXES:
        if model_lower.startswith(prefix):
            return True
    # Unknown model -- exclude by default for safety
    return False


def load_entry(path: Path) -> dict | None:
    """Load a corpus JSON entry, return None on error."""
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        print(f"  Warning: skipping {path}: {exc}", file=sys.stderr)
        return None


def select_representative(
    entries: list[tuple[Path, dict]],
    limit: int,
    seed: int = 42,
) -> list[tuple[Path, dict]]:
    """Select a representative subset covering all stages and categories.

    Strategy: stratified sampling by phase, then by category within each
    phase.  Falls back to random if there are fewer entries than limit.
    """
    if len(entries) <= limit:
        return entries

    by_phase: dict[str, list[tuple[Path, dict]]] = {}
    for path, entry in entries:
        phase = entry.get("phase", "?")
        by_phase.setdefault(phase, []).append((path, entry))

    rng = random.Random(seed)
    selected: list[tuple[Path, dict]] = []
    phases = sorted(by_phase.keys())
    per_phase = max(1, limit // len(phases))

    for phase in phases:
        pool = by_phase[phase]
        # Further stratify by category
        by_cat: dict[str, list[tuple[Path, dict]]] = {}
        for p, e in pool:
            cat = e.get("category", e.get("task_id", "?").rsplit("-", 1)[0])
            by_cat.setdefault(cat, []).append((p, e))

        cats = sorted(by_cat.keys())
        per_cat = max(1, per_phase // max(len(cats), 1))
        for cat in cats:
            sample = by_cat[cat]
            rng.shuffle(sample)
            selected.extend(sample[:per_cat])

    # Top up if we're short
    if len(selected) < limit:
        remaining = [(p, e) for p, e in entries if (p, e) not in selected]
        rng.shuffle(remaining)
        selected.extend(remaining[: limit - len(selected)])

    return selected[:limit]


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract open-weight clean subset")
    parser.add_argument("--corpus-dir", type=Path, default=Path("corpus"),
                        help="Root corpus directory")
    parser.add_argument("--output-dir", type=Path, default=Path("clean"),
                        help="Output directory for clean subset")
    parser.add_argument("--limit", type=int, default=200,
                        help="Max programs in clean subset (default: 200)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for sampling")
    args = parser.parse_args()

    if not args.corpus_dir.is_dir():
        print(f"Error: {args.corpus_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    # 1. Scan all entries
    print(f"Scanning {args.corpus_dir} ...")
    all_entries: list[tuple[Path, dict]] = []
    open_entries: list[tuple[Path, dict]] = []
    model_counts: dict[str, int] = {}

    for path in sorted(args.corpus_dir.rglob("*.json")):
        if path.name in ("manifest.json", "schema.json"):
            continue
        entry = load_entry(path)
        if entry is None:
            continue
        model = entry.get("model", "unknown")
        model_counts[model] = model_counts.get(model, 0) + 1
        all_entries.append((path, entry))
        if is_open_weight(model):
            open_entries.append((path, entry))

    print(f"Total entries: {len(all_entries)}")
    print(f"Open-weight entries: {len(open_entries)}")
    print(f"Model breakdown:")
    for model, count in sorted(model_counts.items(), key=lambda x: -x[1]):
        tag = "OPEN" if is_open_weight(model) else "PROP"
        print(f"  [{tag}] {model}: {count}")

    if not open_entries:
        print("No open-weight entries found.  Nothing to extract.", file=sys.stderr)
        sys.exit(1)

    # 2. Select representative subset
    selected = select_representative(open_entries, args.limit, args.seed)
    print(f"Selected {len(selected)} entries for clean subset")

    # 3. Write to output dir
    programs_dir = args.output_dir / "programs"
    programs_dir.mkdir(parents=True, exist_ok=True)

    manifest_entries: list[dict] = []
    for path, entry in selected:
        dest = programs_dir / path.name
        shutil.copy2(path, dest)
        manifest_entries.append({
            "id": entry["id"],
            "phase": entry.get("phase", "?"),
            "task_id": entry.get("task_id", "?"),
            "model": entry.get("model", "unknown"),
            "tk_tokens": entry.get("tk_tokens", 0),
            "score": entry.get("judge", {}).get("score", 0),
            "file": path.name,
        })

    # 4. Write manifest
    manifest = {
        "description": "Clean open-weight-only subset of the toke corpus",
        "selection_criteria": "Only programs generated by open-weight models (DeepSeek, Qwen, Llama, mechanical generators). No proprietary model outputs (Claude, GPT, Grok, Gemini).",
        "total_entries": len(manifest_entries),
        "seed": args.seed,
        "models": sorted(set(e["model"] for e in manifest_entries)),
        "phases": sorted(set(e["phase"] for e in manifest_entries)),
        "entries": sorted(manifest_entries, key=lambda e: e["id"]),
    }
    manifest_path = args.output_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"Written {len(manifest_entries)} entries to {programs_dir}/")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
